CXXFLAGS = -fPIC -O2 -DNDEBUG -g0 -std=c++11

CORESOURCES=image/image.cpp transform/transform.cpp $(wildcard maniac/*.cpp) $(wildcard encoding/*.cpp) io.cpp
OBJ = $(CORESOURCES:.cpp=.o)

libfuif.a: $(OBJ)
	$(AR) cr $@ $^

clean:
	rm -f $(OBJ) libfuif.a
